### ISSUE TITLE
Client blocking

### ISSUE THREAD

**Issue by dyshay** [kralamoure/retroproxy#2]
The client remains blocked 

I made some tests, I could not connect to the official server, it is necessary to make particular manipulations ?

**Comment by happybydefault** [comment]
Hi, @Dyshay!

It seems the default login server address needed to be updated from `co-retro.ankama-games.com:443` to `dofusretro-co-production.ankama-games.com:443`. I made this change today, and I also updated the `README.md` file.

I tried connecting to the Boune server using the new version of the proxy (v1.5.0), and it's working properly. Tell me if it's working for you now or if you need any assistance — I'm happy to help.

**Comment by dyshay** [comment]
It's okay thanks for the update
