### ISSUE TITLE
Send package from client

### ISSUE THREAD

**Issue by dyshay** [kralamoure/retroproxy#3]
I would like to know if you have problems using the packet to send the server a path request for example

Example: 
GA001

Do you have discord ?

**Comment by happybydefault** [comment]
Hi @Dyshay, sorry about the delay.

There's no problem in sending packets from the client to the server, so maybe you are doing something wrong. Look:

[Screencast from 2023-05-03 21-23-10.webm](https://user-images.githubusercontent.com/13039644/236087521-4a56515f-21dc-4e7b-92b2-016eb28543ea.webm)

If you are still needing help with this, just let me know and I'll try to help you on Discord.
