### ISSUE TITLE
Hello can You fix the package not Send from client !

### ISSUE THREAD

**Issue by AsmihMarouane** [kralamoure/retroproxy#4]
![image](https://github.com/kralamoure/retroproxy/assets/133156367/215fc36a-f0f4-460c-bfbe-f438134f390c)
![image](https://github.com/kralamoure/retroproxy/assets/133156367/1b244b1b-6eff-45d8-ba58-bd329248ae27)
![image](https://github.com/kralamoure/retroproxy/assets/133156367/3d1222f0-6906-4232-ae99-154fa4d328e3)
 I am reaching out to you because I am currently facing a problem and I believe you could offer valuable assistance.
 My discord : .kawik
 Thank you in advance for considering my request. Your expertise would make a significant difference, and I truly value your support.

Best regards,

**Comment by happybydefault** [comment]
Hi, @kawik1. I'm so sorry I hadn't responded yet! Could you eventually solve the problem? Would my help now still be relevant?

**Comment by AsmihMarouane** [comment]
Yes, I still have the problem. If you could provide me with more information on how it works or have a brief 10-minute discussion, I would greatly appreciate it.

**Comment by happybydefault** [comment]
@kawik1 Yeah, sure! What's your full Discord tag? Mine is `happybydefault`.
